-- MySQL Script generated by MySQL Workbench
-- Sat Jun 16 18:36:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nounou
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nounou
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nounou` DEFAULT CHARACTER SET utf8 ;
USE `nounou` ;

-- -----------------------------------------------------
-- Table `nounou`.`Nounous`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nounou`.`Nounous` (
  `idNounous` INT NOT NULL AUTO_INCREMENT,
  `Prénom` VARCHAR(45) NULL,
  `Portable` VARCHAR(10) NULL,
  `Age` INT(2) NULL,
  `Présentation` VARCHAR(200) NULL,
  `Expérience` VARCHAR(100) NULL,
  `Visible` TINYINT NULL,
  PRIMARY KEY (`idNounous`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nounou`.`Parents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nounou`.`Parents` (
  `idParents` INT NOT NULL AUTO_INCREMENT,
  `Ville` VARCHAR(45) NOT NULL,
  `Informations Générales` VARCHAR(200) NULL,
  PRIMARY KEY (`idParents`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nounou`.`Horaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nounou`.`Horaires` (
  `idHoraires` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Heure Début` TIME NOT NULL,
  `Heure Fin` TIME NOT NULL,
  PRIMARY KEY (`idHoraires`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nounou`.`Enfants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nounou`.`Enfants` (
  `idEnfants` INT NOT NULL AUTO_INCREMENT,
  `Prénom` VARCHAR(45) NOT NULL,
  `Date de Naissance` DATE NOT NULL,
  `Restrictions Alimentaires` VARCHAR(200) NULL,
  `idParents` INT NOT NULL,
  PRIMARY KEY (`idEnfants`),
  INDEX `fk_Enfants_Parents1_idx` (`idParents` ASC),
  CONSTRAINT `fk_Enfants_Parents1`
    FOREIGN KEY (`idParents`)
    REFERENCES `nounou`.`Parents` (`idParents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nounou`.`Langues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nounou`.`Langues` (
  `idLangue` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Visible` TINYINT NULL,
  PRIMARY KEY (`idLangue`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nounou`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nounou`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `MDP` VARCHAR(200) NOT NULL,
  `idNounous` INT NULL,
  `idParents` INT NULL,
  PRIMARY KEY (`idUtilisateur`),
  INDEX `fk_Utilisateur_Nounous_idx` (`idNounous` ASC),
  INDEX `fk_Utilisateur_Parents1_idx` (`idParents` ASC),
  CONSTRAINT `fk_Utilisateur_Nounous`
    FOREIGN KEY (`idNounous`)
    REFERENCES `nounou`.`Nounous` (`idNounous`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_Parents1`
    FOREIGN KEY (`idParents`)
    REFERENCES `nounou`.`Parents` (`idParents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nounou`.`Parle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nounou`.`Parle` (
  `idLangue` INT NOT NULL,
  `idNounous` INT NOT NULL,
  `Niveau` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLangue`, `idNounous`),
  INDEX `fk_Langues_has_Nounous_Nounous1_idx` (`idNounous` ASC),
  INDEX `fk_Langues_has_Nounous_Langues1_idx` (`idLangue` ASC),
  CONSTRAINT `fk_Langues_has_Nounous_Langues1`
    FOREIGN KEY (`idLangue`)
    REFERENCES `nounou`.`Langues` (`idLangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Langues_has_Nounous_Nounous1`
    FOREIGN KEY (`idNounous`)
    REFERENCES `nounou`.`Nounous` (`idNounous`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nounou`.`Garde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nounou`.`Garde` (
  `idNounous` INT NOT NULL,
  `idHoraires` INT NOT NULL,
  `Régulier` TINYINT NOT NULL,
  `Date Début` DATE NULL,
  `Date Fin` DATE NULL,
  `Langue` TINYINT NULL,
  `nbr_enfant_max` INT NULL,
  `Prix` INT NULL,
  `Note` INT NULL,
  `Appreciation` VARCHAR(300) NULL,
  PRIMARY KEY (`idNounous`, `idHoraires`),
  INDEX `fk_Nounous_has_Disponibilités_Disponibilités1_idx` (`idHoraires` ASC),
  INDEX `fk_Nounous_has_Disponibilités_Nounous1_idx` (`idNounous` ASC),
  CONSTRAINT `fk_Nounous_has_Disponibilités_Nounous1`
    FOREIGN KEY (`idNounous`)
    REFERENCES `nounou`.`Nounous` (`idNounous`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nounous_has_Disponibilités_Disponibilités1`
    FOREIGN KEY (`idHoraires`)
    REFERENCES `nounou`.`Horaires` (`idHoraires`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nounou`.`Enfants_Gardé`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nounou`.`Enfants_Gardé` (
  `idEnfants` INT NOT NULL,
  `idNounous` INT NOT NULL,
  `idHoraires` INT NOT NULL,
  PRIMARY KEY (`idEnfants`, `idNounous`, `idHoraires`),
  INDEX `fk_Enfants_has_Propose_Propose1_idx` (`idNounous` ASC, `idHoraires` ASC),
  INDEX `fk_Enfants_has_Propose_Enfants1_idx` (`idEnfants` ASC),
  CONSTRAINT `fk_Enfants_has_Propose_Enfants1`
    FOREIGN KEY (`idEnfants`)
    REFERENCES `nounou`.`Enfants` (`idEnfants`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enfants_has_Propose_Propose1`
    FOREIGN KEY (`idNounous` , `idHoraires`)
    REFERENCES `nounou`.`Garde` (`idNounous` , `idHoraires`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;